### ISSUE TITLE
Problem with `IniFilename`

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre-meshviewer#47]
Hello,

I can't deal with this right now so I'm opening a ticket for remainder.

[how to use ogre-meshviewer in windows](https://forums.ogre3d.org/viewtopic.php?p=556072#p556072)

```
Traceback (most recent call last):
  File "D:\ogre-meshviewer_24.06-win64\ogre_mesh_viewer.py", line 843, in <module>
    app.initApp()
  File "D:\ogre-meshviewer_24.06-win64\ogre_mesh_viewer.py", line 722, in setup
    ImGui.GetIO().IniFilename = self.getFSLayer().getWritablePath("imgui.ini")
TypeError: in method 'ImGuiIO_IniFilename_set', argument 2 of type 'char const *'

```

**Comment by paroj** [comment]
cannot reproduce here

**Comment by sercero** [comment]
> cannot reproduce here

I think its a windows thing

**Comment by paroj** [comment]
I tested the windows package via wine

**Comment by sercero** [comment]
> I tested the windows package via wine

Hmmm haha

Don't worry I'll test it in a *real* windows, and see what happens.
😂

**Comment by sercero** [comment]
OK, I didn't have the problem either.

Tested on: `Windows 10 Pro 22H2`

Perhaps the guy had Windows 11.

**Comment by paroj** [comment]
should not make a difference
